db_file: "face_identity.db"
dataset_dir: "dataset"
preprocessed_dataset_dir: "preprocessed-dataset"
face_detector_backend: "yunet"
# facenet model input size is 160x160, embedding size is 128
embedding_model: "Facenet"
L2_threshold: 90
